ShakerSort Class Reference
library that controls reading from and writing to the standard streams.
#include <ShakerSort.h>
Public Member Functions
ShakerSort ()
Constructor taking no param.
void start ()
Private Member Functions
void fillArrayWithRandomValues ()
void getArraySizeInput ()
void readArrayFromFile ()
void saveArrayToFile (int[], const std::string &) const
void shakerSortAscending (int[], int)
void shakerSortDescending (int[], int)
Static Private Member Functions
static std::string getExecutionTime (long &)
static std::string getFileName ()
static void printAsteriskLine ()
static void printExecutionTime (long &, const std::string &)
static void swap (int &, int &)
Private Attributes
int SIZE_OF_ARRAY
stores size of array
Detailed Description
library that controls reading from and writing to the standard streams.
 Module Name: Shaker Sort.
 Author: Faisal Javed
 Date of Creation: 10th November, 2022
 Purpose: Class is a user-defined data type, which holds its own data members and member functions, which can be accessed and used by creating an instance of that class. Defining class ShakerSort which contains variables, methods and constructors.
Constructor & Destructor Documentation
ShakerSort()
ShakerSort::ShakerSort ()
Constructor taking no param.
Postcondition
Post Condition - initialized array size var to 0.
variable ShakerSort::SIZE_OF_ARRAY is initialized in the constructor.
                       {
    SIZE_OF_ARRAY = 0;
}
References SIZE_OF_ARRAY.
Member Function Documentation
fillArrayWithRandomValues()
void ShakerSort::fillArrayWithRandomValues () [private]
The pseudo-random number generator is initialized using the argument passed as seed.
 For every different seed value used in a call to srand, the pseudo-random number generator can be expected to generate a different succession of results in the subsequent calls to rand. passed time(0) function that returns the current time in seconds.
creating an array pointer of integers of size ShakerSort::SIZE_OF_ARRAY
using rand() function to generate a random value from 1 to SIZE_OF_ARRAY
calling ShakerSort::saveArrayToFile to save the array to a file.
                                           {
    srand(time(0));
    int *array = new int[SIZE_OF_ARRAY];
    for (int i = 0U; i < SIZE_OF_ARRAY; i++) {
        array[i] = rand() % SIZE_OF_ARRAY + 1;
    }
    saveArrayToFile(array, getFileName());
}
References getFileName(), saveArrayToFile(), and SIZE_OF_ARRAY.
Referenced by start().
getArraySizeInput()
void ShakerSort::getArraySizeInput () [private]
printing a statement to console
storing the size of array from input
returns [true] if either (or both) failbit or the badbit error state flags is set for the stream. if we encounter a string it will return true as it failed to parse it as an integer.
we will clear the error state flags and re-parse the stream properly.
function is used which is used to ignore or clear one or more characters from the input buffer.
calling ShakerSort::getArraySizeInput recursively
                                   {
    cout << "Enter array size: ";
    cin >> SIZE_OF_ARRAY;
    if(cin.fail()){
        cout << endl << "Wrong input. Try again" << endl << endl;
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
        getArraySizeInput();
    }
}
References getArraySizeInput(), and SIZE_OF_ARRAY.
Referenced by getArraySizeInput(), and start().
getExecutionTime()
string ShakerSort::getExecutionTime (long & executionTime) [static], [private]
creating an object of ostringstream class to stream the string into different variables.
if executionTime is greater than 1000000L return value in millisecond
elseif executionTime is greater than 1000L return value in microsecond
else return value in nanoseconds
                                                       {
    ostringstream oss;
    oss << fixed << showpoint << setprecision(5);
    if(executionTime > 1000000L){
        oss << executionTime/1000000L << " millisecond";
    }
    else if(executionTime > 1000L) {
        oss << executionTime/1000L << " microseconds";
    }
    else {
        oss << executionTime << " nanoseconds";
    }
    return oss.str();
}
Referenced by printExecutionTime().
getFileName()
string ShakerSort::getFileName () [static], [private]
return the file name
                               {
    return "shaker_sort_output.txt";
}
Referenced by fillArrayWithRandomValues(), and readArrayFromFile().
printAsteriskLine()
void ShakerSort::printAsteriskLine () [static], [private]
printing * line to console
                                   {
    cout << "***********************************************************" << endl;
}
Referenced by printExecutionTime().
printExecutionTime()
void ShakerSort::printExecutionTime (long & , const std::string &) [static], [private]
print a * line to console.
print execution time to console.
print a * line to console.
printing newline
                                                                               {
    printAsteriskLine();
    cout << "Execution time for " << sortType << " Shaker sort is: " << getExecutionTime(executionTime) << endl;
    printAsteriskLine();
    cout << endl;
}
References getExecutionTime(), and printAsteriskLine().
Referenced by shakerSortAscending(), and shakerSortDescending().
readArrayFromFile()
void ShakerSort::readArrayFromFile () [private]
creating an object of input file stream to perform read operations. takes ShakerSort::getFileName() function as an argument which returns the file name.
Checks if the file is NOT opened then throw an error and stop the program.
throw is a keyword to define custom exceptions. We will
Exceptions
runtime_error exception if the file is unable to open.
creating an array for shaker sort ascending order
creating an array for shaker sort descending order
creating a variable to store values from file after each iteration.
creating a variable to loop through the array
storing the value to array from stream
storing the value to array from stream
incrementing the index
calling ShakerSort::shakerSortAscending to sort the array
calling ShakerSort::shakerSortDescending to sort the array
                                   {
    ifstream fileStream(getFileName());
    if (!fileStream.is_open()) {
        throw invalid_argument("Unable to read file.");
    }
    int *shakerSortAscArray = new int[SIZE_OF_ARRAY];
    int *shakerSortDescArray = new int[SIZE_OF_ARRAY];
    int arrayElement;
    int index = 0U;
    while(fileStream >> arrayElement){
        shakerSortAscArray[index] = arrayElement;
        shakerSortDescArray[index] = arrayElement;
        index++;
    }
    shakerSortAscending(shakerSortAscArray, SIZE_OF_ARRAY);
    shakerSortDescending(shakerSortDescArray, SIZE_OF_ARRAY);
}
References getFileName(), shakerSortAscending(), shakerSortDescending(), and SIZE_OF_ARRAY.
Referenced by start().
saveArrayToFile()
void ShakerSort::saveArrayToFile (int [], const std::string &) const [private]
creating an object of output file stream to perform write operations. takes filename as an argument.
Checks if the file is NOT opened then throw an error and stop the program.
throw is a keyword to define custom exceptions. We will
Exceptions
runtime_error exception if the file is unable to open.
using for loop to iterate through array U as a suffix to 0 means only unsigned values
store the array value to file.
closing the outputStream after performing the write operations.
                                                                          {
    ofstream outputStream(fileName);
    if (!outputStream.is_open()) {
        throw invalid_argument("Unable to open a file to write operations.");
    }
    for(int i = 0U; i < SIZE_OF_ARRAY; i++){
        outputStream << array[i] << " ";
    }
    outputStream.close();
}
References SIZE_OF_ARRAY.
Referenced by fillArrayWithRandomValues(), shakerSortAscending(), and shakerSortDescending().
shakerSortAscending()
void ShakerSort::shakerSortAscending (int array[], int arraySize) [private]
creating a bool flag to check base conditions of shaker sort
storing the time point representing the current time in startTime variable.
using for loop to iterate through array U as a suffix to 0 means only unsigned values
setting flag to false by default.
using for loop to iterate through array
if the current element is greater than the next element then swap
calling function ShakerSort::swap to swap values of 2 integers.
setting flag to true if swap is occurred.
if bool is set to false it means no swap is occurred so the loop will break as the array is already sorted.
reducing array size so as to not include the sorted element in next iteration.
setting flag to false by default for another loop.
using for loop to iterate through array
if the previous element is greater than the current element then swap
calling function ShakerSort::swap to swap values of 2 integers.
setting flag to true if swap is occurred.
if bool is set to false it means no swap is occurred so the loop will break as the array is already sorted.
storing the time point representing the current time in endTime variable.
calculating the elapsed time in millisecond from startTime and endTime.
calling ShakerSort::printExecutionTime to print the execution time.
calling ShakerSort::saveArrayToFile to save the array to a file.
                                                               {
    bool swapped;
    auto startTime = high_resolution_clock::now();
    for(int i = 0U; i < arraySize; i++){
        swapped = false;
        for(int j = i; j < arraySize-1; j++){
            if(array[j] > array[j+1]){
                swap(array[j], array[j+1]);
            }
            swapped = true;
        }
        if(!swapped)
            break;
        arraySize--;
        swapped = false;
        for(int j = arraySize-1; j > i; j--){
            if(array[j] < array[j-1]){
                swap(array[j], array[j-1]);
            }
            swapped = true;
        }
        if(!swapped)
            break;
    }
    auto endTime = high_resolution_clock::now();
    long executionTime = duration_cast<nanoseconds>(endTime - startTime).count();
    printExecutionTime(executionTime, "Ascending");
    saveArrayToFile(array, "shaker_sort_asc.txt");
}
References printExecutionTime(), saveArrayToFile(), and swap().
Referenced by readArrayFromFile().
shakerSortDescending()
void ShakerSort::shakerSortDescending (int array[], int arraySize) [private]
creating a bool flag to check base conditions of shaker sort
storing the time point representing the current time in startTime variable.
using for loop to iterate through array U as a suffix to 0 means only unsigned values
setting flag to false by default.
using for loop to iterate through array
if the current element is smaller than the next element then swap
calling function ShakerSort::swap to swap values of 2 integers.
setting flag to true if swap is occurred.
if bool is set to false it means no swap is occurred so the loop will break as the array is already sorted.
reducing array size so as to not include the sorted element in next iteration.
setting flag to false by default for another loop.
using for loop to iterate through array
if the previous element is smaller than the current element then swap
calling function ShakerSort::swap to swap values of 2 integers.
setting flag to true if swap is occurred.
if bool is set to false it means no swap is occurred so the loop will break as the array is already sorted.
storing the time point representing the current time in endTime variable.
calculating the elapsed time in millisecond from startTime and endTime.
calling ShakerSort::printExecutionTime to print the execution time.
calling ShakerSort::saveArrayToFile to save the array to a file.
                                                                {
    bool swapped;
    auto startTime = high_resolution_clock::now();
    for(int i = 0U; i < arraySize; i++){
        swapped = false;
        for(int j = i; j < arraySize-1; j++){
            if(array[j] < array[j+1]){
                swap(array[j], array[j+1]);
            }
            swapped = true;
        }
        if(!swapped)
            break;
        arraySize--;
        swapped = false;
        for(int j = arraySize-1; j > i; j--){
            if(array[j] > array[j-1]){
                swap(array[j], array[j-1]);
            }
            swapped = true;
        }
        if(!swapped)
            break;
    }
    auto endTime = high_resolution_clock::now();
    long executionTime = duration_cast<nanoseconds>(endTime - startTime).count();
    printExecutionTime(executionTime, "Descending");
    saveArrayToFile(array, "shaker_sort_desc.txt");
}
References printExecutionTime(), saveArrayToFile(), and swap().
Referenced by readArrayFromFile().
start()
void ShakerSort::start ()
calling ShakerSort::getArraySizeInput to get the array size
calling ShakerSort::fillArrayWithRandomValues to fill the array with random values
calling ShakerSort::readArrayFromFile to read file and perform shaker sort and calculate execution time.
                       {
    getArraySizeInput();
    fillArrayWithRandomValues();
    readArrayFromFile();
}
References fillArrayWithRandomValues(), getArraySizeInput(), and readArrayFromFile().
Referenced by main().
swap()
void ShakerSort::swap (int & item1, int & item2) [static], [private]
using a temporary variable to store the first value.
assigning the value of 2nd variable to first variable.
assigning the value of first variable stored in a temporary variable to the 2nd variable.
                                            {
    int temp = item1;
    item1 = item2;
    item2 = temp;
}
Referenced by shakerSortAscending(), and shakerSortDescending().
Member Data Documentation
SIZE_OF_ARRAY
int ShakerSort::SIZE_OF_ARRAY [private]
stores size of array
Referenced by fillArrayWithRandomValues(), getArraySizeInput(), readArrayFromFile(), saveArrayToFile(), and ShakerSort().
The documentation for this class was generated from the following files:
ShakerSort.h
ShakerSort.cpp